//
//  ProgressBarDraw.swift
//  Gouda
//
//  Created by Victoria Melendez on 11/30/16.
//  Copyright © 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    public dynamic class func drawProgressBar(frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 16), progress: CGFloat = 200) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let themeGold = UIColor(red: 0.000, green: 0.475, blue: 0.420, alpha: 1.000)

        //// Progress Border Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + fastFloor((frame.width - 298) * 0.50000 + 0.5), y: frame.minY + 1, width: 298, height: 14), cornerRadius: 7)
        themeGold.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// Progress Active Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 1, y: 1, width: progress, height: 14), cornerRadius: 7)
        themeGold.setFill()
        progressActivePath.fill()
        themeGold.setStroke()
        progressActivePath.lineWidth = 1
        progressActivePath.stroke()
    }

}
